appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: U2M4ZUREQxkUCHhKpf8DhaMcdS+ULPG9uAPjKf/PUEKd83HPuo4WV3Z4lPLeD3C0Mvh5LR8tLRCsGCdNOF6TUbiez7LHsHaCtsRiDWccocPzzOY+Rjc7D6CX7c5GWD/JcVPRlOSy8SIYJjM7sx7IG4r8GpfTBdMz/2W2KIG9fe3KcAnfzm2IeNwHkWSiO4vlBElaTxy+6W+gF3s6l/XOdA68fTmxgrKdHGctWWB1ae26MPrLJ24QHi5GRK+wAxIOcL4dHOggsGCA2XO/WOb03rF1qsFSfENFMBTz0AOmGtsT6tr1BRZTxNJY71WrrbSplgZAtby/U8fqAqt0DrA2IpZuQ9Y/zIGgyz7IVbrilfaBbZF2OfB2ba1J+eW4P0FhfFg2eugumsYtyjMbJ6cNtyiNgBLBg3dZ3pwTINYW4857ck3Q+afY8ZzDObgrX1PZybBomhjPHjpD8YBL0E5pFkdXujAo+bww//dArPK7+hJoVGNar8nMrOApaH4Daaoe1QLiAvIPmshHVnp1hQHvP+3Gnz3EHyyw6HfTHy8on413j65uxxU38E5z+hb9DhfR5933nqjIb3Rd/vPn8ffi6jC1Kxso6Estz2Ufc1mBVFoOju9lU89eU/H0auFGxJIkYUV/3sYHMS0WwuogK+MJSBWQpr0ojJ0snWNjIQuN19M=}
